#!/bin/bash

# Teacher Application Diagnostic Script
# This script will help debug why teacher applications aren't appearing in the admin panel

echo "====================================="
echo "Teacher Application Diagnostic Test"
echo "====================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
BACKEND_URL="http://localhost:5145"
FRONTEND_URL="http://localhost:3001"

echo -e "${BLUE}1. Testing Backend API Endpoints${NC}"
echo "===================================="
echo ""

echo -e "${YELLOW}1a. Testing GET /api/teachers/applications (without filter)${NC}"
echo "Command: curl -H 'Authorization: Bearer YOUR_ADMIN_TOKEN' \"${BACKEND_URL}/api/teachers/applications\""
echo "Expected: Returns all applications (both pending and processed)"
echo ""

echo -e "${YELLOW}1b. Testing GET /api/teachers/applications?status=Pending${NC}"
echo "Command: curl -H 'Authorization: Bearer YOUR_ADMIN_TOKEN' \"${BACKEND_URL}/api/teachers/applications?status=Pending\""
echo "Expected: Returns only pending applications"
echo ""

echo -e "${YELLOW}1c. Testing GET /api/teachers/debug/claims${NC}"
echo "Command: curl -H 'Authorization: Bearer YOUR_ADMIN_TOKEN' \"${BACKEND_URL}/api/teachers/debug/claims\""
echo "Expected: Shows your JWT claims (should include 'Admin' role)"
echo ""

echo -e "${BLUE}2. Database Query${NC}"
echo "======================================"
echo ""
echo "Run this SQL query in your PostgreSQL client (pgAdmin or psql):"
echo ""
echo "-- Check all teacher applications"
echo "SELECT "
echo "  ta.\"Id\", ta.\"UserId\", ta.\"Status\", ta.\"ApplicationDate\","
echo "  u.\"Username\", u.\"Email\", u.\"FirstName\", u.\"LastName\", u.\"IsAdmin\""
echo "FROM \"TeacherApplications\" ta"
echo "JOIN \"Users\" u ON ta.\"UserId\" = u.\"Id\""
echo "ORDER BY ta.\"ApplicationDate\" DESC"
echo "LIMIT 10;"
echo ""
echo "-- Count pending applications"
echo "SELECT COUNT(*) FROM \"TeacherApplications\" WHERE \"Status\" = 'Pending';"
echo ""
echo "-- Check if your admin user exists and has correct role"
echo "SELECT \"Id\", \"Username\", \"Email\", \"IsAdmin\" FROM \"Users\" WHERE \"IsAdmin\" = true;"
echo ""

echo -e "${BLUE}3. Frontend Console Check${NC}"
echo "======================================"
echo ""
echo "Open http://localhost:3001 in browser"
echo "1. Login with your admin account"
echo "2. Go to Admin Dashboard"
echo "3. Open DevTools (F12) → Console tab"
echo "4. Check for any error messages"
echo "5. Check the Network tab to see the API response:"
echo "   - Look for request to /api/teachers/applications?status=Pending"
echo "   - Check the response body (should contain 'applications' array)"
echo ""

echo -e "${BLUE}4. Step-by-Step Debugging${NC}"
echo "======================================"
echo ""
echo "Step 1: Create a test teacher application"
echo "  - Login as a NON-ADMIN student"
echo "  - Navigate to 'Become a Teacher' page"
echo "  - Fill out and submit the form"
echo "  - You should see success message"
echo ""
echo "Step 2: Check the database"
echo "  - Run the SQL queries above"
echo "  - Verify the new application appears with Status='Pending'"
echo ""
echo "Step 3: Test the API directly"
echo "  - Use Postman or curl with your admin token"
echo "  - Call: GET /api/teachers/applications?status=Pending"
echo "  - Should return the application in the 'applications' array"
echo ""
echo "Step 4: Check the Admin Dashboard"
echo "  - Login as admin"
echo "  - Go to Admin Dashboard"
echo "  - Look for the pending application in the table"
echo "  - Open DevTools Console to check for errors"
echo ""

echo -e "${BLUE}5. Common Issues and Fixes${NC}"
echo "======================================"
echo ""
echo -e "${YELLOW}Issue 1: 401 Unauthorized error${NC}"
echo "  Solution: Your user is not marked as admin in database"
echo "  Fix: UPDATE \"Users\" SET \"IsAdmin\" = true WHERE \"Id\" = YOUR_USER_ID;"
echo ""
echo -e "${YELLOW}Issue 2: Empty 'applications' array returned${NC}"
echo "  Solution: Check if database has any pending applications"
echo "  Fix: Run the SQL SELECT query to verify data exists"
echo ""
echo -e "${YELLOW}Issue 3: Table shows 'No pending applications'${NC}"
echo "  Solution: Frontend is receiving data but not rendering it"
echo "  Fix: Check browser console for JavaScript errors"
echo ""
echo -e "${YELLOW}Issue 4: New application doesn't appear after refresh${NC}"
echo "  Solution: The useEffect might have a dependency issue"
echo "  Fix: Check if auto-refresh interval is set up"
echo ""

echo -e "${GREEN}====================================="
echo "Diagnostic Complete"
echo "=====================================${NC}"
echo ""
echo "Once you run these tests, please share the results."
